apiVersion: v1
kind: Secret
metadata:
  name: admin-auth
  namespace: traefik
type: Opaque
data:
  userfile: YWRtaW46JGFwcjEkNzNweG91ajYkelNibWYxUzZ6N3BLb1lBLnJ0ZkpyMQ==
  # →→ admin:admin →→ admin:$apr1$73pxouj6$zSbmf1S6z7pKoYA.rtfJr1
  ####################### no info about password
  # →→ admin:
  # userfile: YWRtaW46JGFwcjEkMFBEelJ2OUIkNzY5LkdWLm4zNGxBbWgxSjRzY201Lgo=
